### PR TITLE
Release 2.2.6.14

### PR DESCRIPTION
**Pull request by andreaTP**

### CODE REVIEW

**Comment by andreaTP** [comment]
Thanks to @an-tex for the hard work 👍

**Comment by an-tex** [comment]
wohoo thanks for the swift release @andreaTP 🚀

**Comment by an-tex** [comment]
@andreaTP looks like the travis release didn't succeed? artifacts are not showing up on https://mvnrepository.com/artifact/org.akka-js

**Comment by andreaTP** [comment]
@an-tex they are on `repo1`:
https://repo1.maven.org/maven2/org/akka-js/akkajsactor_sjs1_2.13/

**Comment by an-tex** [comment]
ah got it thanks! now they also appeared on central. cheers!

**Pull request merged**
