### PR TITLE
Initial support for akka-stream

### PR DESCRIPTION
**Pull request by solomono**
From StreamDemoNotes
## akka.js
1. plugin.sbt Added akkaJsActorStream
   Note I basically copied the akkaJsStream project expression and changed the minimum
   ## AkkaJSActor 
   1. Mailboxes, Mailbox
      ActorSubscriber in akkaJsActorStream
      requires AbstractActor 
      requires Mailboxes with stackCapacity  
      requires Stash 
      requires Mailbox with DequeBasedMessageQueueSemantics
2. Done, NotUsed, ByteIterator, ByteString, TokenBucket copied to shared to satisfy various classes in akkaJsActorStream
   1. Functions and Tuples
      Generated by sbt boilerplate. Copied generator code, was not  successful in using boilerplate plugin, must fix
## AkkaJSStream
1. ActorSystem 
   1. Modified the registterExtension method to reflect the single threaded environment in Javascript. Removed the use of CountdownLatch and ConcurrentHashMap
      This resolves an issue hanging in the call to with Source.actorRef  as wel as the call to FlowNames(system).name.copy(namePrefix)) in ActorMaterializer.apply
2. ActorMaterializerImpl.scala
   1. In the method materializeAtomic removed the case for TLS Module 
   2. In the actorOf in the case for RepointableActorRef if the actorCell is not started call point
3. Attributes 
   1. Removed the Java API  getAttribute calls and reimplemented where the Scala calls were dependent
   2. Implemented URLEncoder to ScalaJS URIUtils.encodeURI(n)
4. FramingTruncation AsPublisher
   1. Java enums. Converted to Scala naively.  
5. GraphInterpreter
   1. scala.concurrent.forkjoin.ThreadLocalRandom
      to java.util.concurrent.ThreadLocalRandom
6. Generated by sbt boilerplate
   1. FanInShape
   2. FanOutShape
   3. GraphApply
   4. UnzipWithApply
   5. ZipWithApply
   6. GraphCreate
   7. UnzipWith
   8. ZipWith

### CODE REVIEW

**Comment by andreaTP** [comment]
That's great!
what I want to work on is:
- try to keep the original ActorSystem file and fix any issue on it externally
- reproduce the build and code generation they have in original Akka and generate code "on the fly" instead including generated files

more over 

> GraphInterpreter : scala.concurrent.forkjoin.ThreadLocalRandom to java.util.concurrent.ThreadLocalRandom

with this I go for a PR on akka

**Comment by andreaTP** [comment]
BTW thanks a lot for the great contribution!

**Comment by andreaTP** [comment]
ThreadLocalRandom is on the way:
https://github.com/akka/akka/pull/20877#issuecomment-230413693

**Comment by solomono** [comment]
My initial goal was to demonstrate the goal of compiling  akka streams  against Scala.js was feasible 
Now we have established that, in the future I will  keep upmost in my mind  your objective of eventually have the akka project cross compile for JavaScript which requires  minimizing the  differences between JDK/JVM and ScalaJS versions  
1. Concerning the code generated by sbt boilerplate I did make some efforts to use that mechanism . I placed the source  files in src/main/boilerplate instead of shared and added the enableplugins directive but was unsuccessful . I am certain with further effort I will resolve this issue 
2. To reiterate from above I recognize we have a general goal  of striving to minimize code differences 
I notice some cases where classes that can be confined in the config are renamed and certainly that is one approach where this is possible 
With regard to the issue in ActorSystem I don't see how this can be accomplished. I believe it is similar the the problem in ActorMaterializerImpl
I.e. Dependency between logical threads of control . I believe the problem in ActorSystem is the use of CountdownLatch which in the Java implementation uses signals ( wait and notify ) 
I believe some uses in JavaScript result in awaiting signals which will never come 
ActorSystem.registerExtension calls a tail recursive findExtension which calls await on the countdownlatch.  So we have the sole  thread awaiting a signal never yielding so the signaling thread can run . Since it is tail recursive it does not run of out stack space ( I assume that concept is valid in JavaScript ) so recursion continued without end and it hangs . In the browser if I pause the execution and then continue I see the code always in the same place 
I don't know how we can solve this problem generally as the registerExtension method is called from many places 
I believe these types of issues may be prevalent 
What are your thoughts on this ? 
3. I see that your pull request for the change to  GraphInterpreter been merged.
I will be on the lookout  for similar cases

**Comment by solomono** [comment]
To clarify I believe given my limited knowledge  that the only possible implementation of await ( Future.await or CountdownLatch , etc )  on Javscript is a trivial one ( perhaps just returning ) since blocking is not possible
In ActorSystem.findExtension and ActorMaterialization apply this results in unlimited recursion 
In ActorMaterializationImpl.actorOf this results 
In an Exception

In some cases I believe the entire code may be  restructured to use Scala async , but to be effective this  will most probably require  a rewrite of the entire call chain, which is unlikely in many of our use cases. 
But it may be feasible in Scalatest

**Comment by andreaTP** [comment]
ok I think we can simply choose how will make the job done :-)

1 -> pick you I think I can assign this task to me and open an issue regarding it
2 -> this unfortunately is a dirty hack i try to explain it:
first we basically disable CountDownLatch providing our own fake implementation:
https://github.com/unicredit/akka.js/blob/master/akka-js-actor/js/src/main/scala/java/util/concurrent/CountDownLatch.scala
then we fake the Await condition by overriding Await itself like here:
https://github.com/unicredit/akka.js/blob/master/akka-js-actor/js/src/main/scala/akka/event/Await.scala

doing so we have a completely async initialization (I hope I'm not forgetting anything).

I will check if is possible to do something similar for ActorMaterializer, haven't looked in depth.
Let me know if you want to look into yourself.

3 -> yes I did it previously, I have some sort of agreement with akka guys :-)

As a general rule we can open issues on specific tasks and continue the work on the branch until we consider it stable enough to merge into master.
is that ok for you?

**Comment by solomono** [comment]
Yes that is ok 
You can open the tasks for the items you mentioned. 
1. If you have immediate knowledge of how to get boilerplate to work please go on ahead, I was going to try my usual tactic of trial and error which I presumed would bear fruit at some point 
2. Yes what you propose might be possible for ActorSystem.registerextension 
3. I made  various attempts  for ActorMaterialisationImpl . I would like to learn from your experiences in resolving these types of issues in 2 and 3 

I will open an issue regarding Source.actorPublisher resulting in a JavaScript error. Perhaps you might have insight there

**Pull request merged**
