### PR TITLE
adding enqueueFirst to mailbox

### PR DESCRIPTION
**Pull request by colinrgodsey**
needed for UnboundedDequeBasedMessageQueueSemantics semantics, needed
for a functioning stash.

### CODE REVIEW

**Comment by andreaTP** [comment]
Thanks a lot for this contribution!
You pointed out an implementation that is diverging too much from Akka without good reasons (too me at least :-) )

Accordingly to Akka implementation:
https://github.com/akka/akka/blob/bd8fcc9d9aeafc2c49745e7519d13b3e0abc18e6/akka-actor/src/main/java/akka/dispatch/AbstractNodeQueue.java#L79

the `add` method itself prepend elements to the queue.
I prefer to not provide additional methods that are not present in original Akka until they are really necessary.

What happens here is that the implementation itself of `UnboundedMailbox.MessageQueue` is incorrectly diverging.
https://github.com/akka/akka/blob/4acc1cca6a27be0ff80f801de3640f91343dce94/akka-actor/src/main/scala/akka/dispatch/Mailbox.scala#L615

Here it looks like it is backed by a ConcurrentLinkedQueue that is already present in Scala.Js ( https://github.com/scala-js/scala-js/blob/608baf718e4366dfdcb0745f13facb2b438344f6/javalib/src/main/scala/java/util/concurrent/ConcurrentLinkedQueue.scala ) and then a naive implementation is probably totally possible right now.

Could you please check if this is the case?

Thanks a lot!

**Comment by colinrgodsey** [comment]
So im having trouble finding where this happens in akka, but as far as i remember when you enable the stash on an actor, it changes the default mailbox implementation from the linkedlist one to a Deque based queue, so LinkedBlockingDeque vs ConcurrentLinkedQueue (more info https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-actor/src/main/scala/akka/actor/Stash.scala#L36):

``` scala
object UnboundedDequeBasedMailbox {   
  class MessageQueue extends LinkedBlockingDeque[Envelope] with UnboundedDequeBasedMessageQueue {     
    final val queue = this   
  }
}

trait UnboundedDequeBasedMessageQueue extends DequeBasedMessageQueue with UnboundedDequeBasedMessageQueueSemantics {
  def enqueue(receiver: ActorRef, handle: Envelope): Unit = queue add handle
  def enqueueFirst(receiver: ActorRef, handle: Envelope): Unit = queue addFirst handle
  def dequeue(): Envelope = queue.poll()
}
```

given that scala's Queue already extends a double linked list (basically a deque), it makes sense to just make the default akkajs mailbox a Deque based one. 

As far as akka's default mailbox queueing to the 'head' of the queue, i think it's just so they can keep a single-link list, and they just read from the end:

https://github.com/akka/akka/blob/bd8fcc9d9aeafc2c49745e7519d13b3e0abc18e6/akka-actor/src/main/java/akka/dispatch/AbstractNodeQueue.java#L137

**Comment by colinrgodsey** [comment]
this could also maybe be solved by extending the mailbox configuration support (see: dealing with reference confs) to actually allow switching between default mailbox types. this could allow for optimized single-link/double-link/limited etc optimized mailboxes like the jvm version.

**Comment by andreaTP** [comment]
actually it should... AFAIR ...
if not I will check in the next days for sure since is mandatory to do that...
and it looks so ( https://github.com/unicredit/akka.js/blob/e2021c9c74e32ded4c05204e81b9054dcefa3c12/akka-js-actor/js/src/main/scala/akka/actor/JSLocalRefProvider.scala#L93 ), but I will check with some examples...

anyhow, for things in the core repo I wish to stay as close as we can to Akka default implementation. So if we want to provide alternative implementations we can just name them differently.

**Comment by colinrgodsey** [comment]
hmm looking at it again, it might just be a fault with RequiresMessageQueue pulling-in/configuring the correct mailbox, but I also do see missing impls for at least that type of mailbox. ill look around later and see if i can find a more akka-compatible solution

**Comment by andreaTP** [comment]
thanks a lot! appreciated!
I hope to fix available mailboxes semantics anyhow in the next days. I file an issue for that.

**Comment by colinrgodsey** [comment]
hmm, so im looking around at available structures for scala trying to find the best match for the ConcurrentLinkedQueue in the standard mailbox, and the ConcurrentLinkedDeque for stash/others.

It really looks like the decision to use the 2 different underlying collections from java is because ConcurrentLinkedDeque doesnt support adding to the 'head' of the queue (at least not in an O(1) way). The MutableList offered by scala seems to be more like a deque than a pure linked list. 

I'll leave the UnboundedMailbox impl untouched, and will probably make another impl for the Deque mailbox that also extends scala's Queue (which extends the MutableList).

Actually, should we update AbstractNodeQueue to use the scala-js version of ConcurrentLinkedQueue? I suppose there's not really much difference, it seems the only difference between a linked-queue (that follows head and tail) and a deque is that a deque gives you O(1) ability to 'pop' from either side. The deque based mailboxes just needs an O(1) addition to both sides, and only 'pops' from one side anyways. 

I think the major reason for picking those two different queues in the Akka impl was probably based on performance differences in the actual concurrency part of it, in scala-js with no concurrency you can get O(1) for all operations needed, just with a single-linked list that tracks first/last (like scala's MutableList and Queue).

**Comment by colinrgodsey** [comment]
im going to wait for the new mailbox impl (#44) and see if we still need something similar to the above changes.

**Pull request closed without merging**
