### PR TITLE
Initial support for akka actors and akka stream tests 

### PR DESCRIPTION
**Pull request by solomono**
# Initial Test Results
## akka testkit

JVM: Run completed in 7 seconds, 858 milliseconds.
[info] Total number of tests run: 61
[info] Suites: completed 11, aborted 0
[info] Tests: succeeded 61, failed 0, canceled 0, ignored 0, pending 0

Node.js Run completed in 6 seconds, 368 milliseconds.
[info] Total number of tests run: 33
[info] Suites: completed 8, aborted 0
[info] Tests: succeeded 21, failed 12, canceled 0, ignored 0, pending 0
## actor tests

JVM: Run completed in 6 minutes, 41 seconds.
[info] Total number of tests run: 1178
[info] Suites: completed 124, aborted 0
[info] Tests: succeeded 1178, failed 0, canceled 0, ignored 1, pending 16

Node.js: Run completed in 2 minutes, 47 seconds.
[info] Total number of tests run: 496
[info] Suites: completed 55, aborted 0
[info] Tests: succeeded 415, failed 81, canceled 0, ignored 0, pending 15
## stream testkit

JVM: Run completed in 1 second, 270 milliseconds.
[info] Total number of tests run: 17
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 17, failed 0, canceled 0, ignored 0, pending 0

Node.js: Run completed in 4 seconds, 115 milliseconds.
[info] Total number of tests run: 17
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 17, failed 0, canceled 0, ignored 0, pending 0
## stream tests

JVM: Run completed in 5 minutes, 19 seconds.
[info] Total number of tests run: 1355
[info] Suites: completed 136, aborted 0
[info] Tests: succeeded 1355, failed 0, canceled 0, ignored 0, pending 13

Node.js: Run completed in 18 minutes, 24 seconds.
[info] Total number of tests run: 1114
[info] Suites: completed 119, aborted 0
[info] Tests: succeeded 970, failed 144, canceled 0, ignored 0, pending 10
# Please note the following
1. There are many redundant changes. Files that were added and them removed within these commits. Many files in the shared directory were added and then removed to conform to the jgit support. These can most probably be squashed in the merge process. 
2. I generalized the assembleAkaLibrary function, adding functionality to support an akka repo outside of the sbt project tree.  Also changed the functionality to some degree. 
3. When building some projects assembleAkkaLibrary is executed multiple times
4. At times the copied files are not picked up, resulting in a build failure,  but on running the same command again it works. This seems to  happen particularly with akka stream tests. 
5. Running some tests may result in  java.net.SocketException: Broken pipe error . Turning off parallel execution"parallelExecution in Test := false,"  seems to resolve the issue at the cost of increased runtime

### CODE REVIEW

**Comment by yawnt** [comment]
Hi @solomono 
wow! thanks for your work! Really appreciate it!

A couple of notes before we merge this:

I see you have edited `build.sbt` and refactored out the code @andreaTP wrote to fetch files from Git. 

This is something we eventually want to do but decided **not to** for now. 
The reason for this is that we need to be able to make granular decisions at the project level (eg: we might want one behavior in `akka-testkit`, another in `akka-actor`). It's very hard to generalize at this stage because we are still figuring it out

Akka is a very complex project, to change both the build system process and to add new behavior (Akka tests) I think is a bit too much for a single PR

For this reason, I would kindly ask you to revert all your changes in `build.sbt` (and other build parts) and either @andreaTP or I will then take care of fixing issues that might arise.

**Comment by yawnt** [comment]
Should you want to propose changes to the build process, do feel free to open an issue, we can discuss it there and PRs can follow from the discussion :)

Thanks again!!!

**Comment by solomono** [comment]
Hi @yawnt 
Good to hear from you 
I  agree that the behavior of the functionality syncing the Akka sources  in each project might diverge further in the future, note that there already some differences which are parameters to the  assembleAkkaSources function . More customized may be added, including functions parameters that can insert behavior at different stages. 
We should also note the the current effect of the generalized function is consistent with the initial version in terms of its effect on the shared folder 
The purpose of this generalization was the DRY principle , which is not  inconsistent with customization
When I had submitted the initial pull request @andreaTP had comments and suggested that I make some changes, which did  initially, but I could not see any appreciable difference from the previous code ( note his particular example for actor--js-testkit had not been implemented as it had nothing previously in shared) 
I have attempted both copy and paste customization and abstraction and neither it seems was satisfying to @andreaTP, and it was not clear to me how to improve on this.
IMHO I believe the build.sbt in the current pull request has a reasonable  foundation for future changes in the Akka sync part of the build process. But as always opinions may vary for legitimate reasons . Indeed both  yourself and @andreaTP have a better understanding than I  of what architecture that will drive this projects' success. That objective is paramount 
In the end, to forestall further delays in merging  , I request that  the   person merging should  include  the version of build.sbt they deem suitable. Or alternatively craft a new one using one of these versions as a base.

**Comment by yawnt** [comment]
Yep, 100% agree, however I would like to split the two parts (tests and build) into separate PRs. 
Maybe there has been some confusion with @andreaTP while communicating, I apologize :)

To sum it up, if you please could revert the changes to `build.sbt` & related in this PR, I'll be more than happy to merge it.

Feel free to open another PR changing **just** `build.sbt`, just so your work doesn't go to waste and we can iterate from there

If that is fine with you, I'd like to add you as a contributor in the `README.md` for your help.
Thanks again!

**Comment by solomono** [comment]
I remain uncertain in how to accomplish this 
The build and the tests are related to the  build.sbt . Previously the contents of the  shared directory ( which contained the unchanged  Akka source ) were links that were in version control  , the new build.sbt submitted last Friday automated the process of  acquiring linking and resolving the Akka source with the changes in Js ) 
As a result I deleted the shared directory and updated the build.sbt to reflect the test projects , by copying and pasting the relevant code to the newly added projects and applying the changes inline as this was the model I found in the build.sbt. This was submitted on Monday and was the basis of a pull request. 
As a response to the comments that arose  from   the copy and paste mechanism I created a parametrized function. 
The other comment was regarding the implementation of the build.sbt provided some more example code but without any difference in senantics so I did not act on it 
I submitted  submitted another pull request on Tuesday. 
Both of these versions yield the same behavior with regard to the contents of the shared directory 
Both of these yield test results the same as that listed above. I.e. both work yield the same results, one employs  copy and paste reuse, the other generalizes the behavior in
A function 
As I mentioned some version of the build.sbt is required to run the tests as the shared directory is now  deleted, but it seems both versions I have provided in two pull requests are unnaceptable 
This is my last week allotted to full time work on this project and I had hoped that I  might spend the remainder of  week creating a roadmap of the changes necessary to move as close  as possible to feature parity  with Akka. 
From next  week I hope to start on a project that is dependent on the progress made in streams  so I won't have the bandwidth to continue the same pace on Akka.js 
It appears we are at impasse,  I don't understand how to accomplish what you require and you are not ready to accept the pull request as is 
Perhaps in the future when my knowledge of git and sbt improves I can make the changes you require 
Thank you for the opportunity I have had thus far 
It has been a delightful learning experience both in technology and process

**Comment by andreaTP** [comment]
@solomono thanks a lot for your effort! What we are asking for is to revert changes to build.sbt in this PR even if this will break the code. We will take care of fixing it! I do prefer to have a linear improvement process especially in a critical file such as the build instead of modifications forth and back. I hope you can understand! Cheers!

**Comment by solomono** [comment]
Ah I see
It seems that you require that I revert the build.sbt to the  initial change to use jgit from last Friday 
Some test projects may not build in this case.
The  actor-js-testkit will function as as it does currently as it has no files that it shares with Akka i.e. the  shared directory is not required .  Some of the other project tests may not build  if any  of  the files in Js depend on a file in shared. 
Please forgive my misunderstanding, I  had previously believed that a commit or PR must  not impact the integrity of the he build .i.e it must result in in  successful build. I believe I can find the version of build.sbt that you require and replace it 
Lastly given my current understanding, the  option which I had suggested was that you do a merge and then change the build.sbt  as necessary . In what I believe you are proposing which I plan to effect is to  replace the build.sbt to the version from last Friday ,which is not consistent with the source files  , and after the merge you would make the change to make it consistent. 
 I must be missing something . Why is it important which version of build.sbt is in the pull request when it will be changed in both cases. Can you please inform me of the principles that makes the  second option superior to the first 
In the future I would hope to apply these principles to maximize my efficiency

**Comment by andreaTP** [comment]
Have a linear progress over changes in git history on build.sbt file! Thanks a lot! @yawnt could you please check and merge? ( We are safely on a beach )

**Comment by andreaTP** [comment]
Branch I mean!

**Comment by yawnt** [comment]
done, thank you very much @solomono :) glad we could work this out!

**Pull request merged**
