### PR TITLE
Fix the IR checking errors related to setting the vals of `Actor`.

### PR DESCRIPTION
**Pull request by sjrd**
Since `Actor` is really a trait, patching its IR with fields, getters and setters from a `class` is nonsensical, and produces invalid IR.

Instead, we simply abuse scalac's internal encoding of `val`s in traits. For concrete `val`s in traits, scalac generates an internal special setter, called from the constructor of the trait to initialize the fields mixed in the subclasses. We simply hijack the mechanism and call those methods reflectively.

This is dependent on the specific encoding of traits by scalac, so it could be broken in a future (binary incompatible) version of Scala. However, for now there seems to be no plan for such changes, and this fixes the IR errors.

### CODE REVIEW

**Comment by sjrd** [comment]
This can be tested locally for the absence of IR checking errors with Scala.js 0.6.19-SNAPSHOT. Apply the following patch:
```diff
diff --git a/build.sbt b/build.sbt
index 57a1293..7b26966 100644
--- a/build.sbt
+++ b/build.sbt
@@ -183,7 +183,8 @@ lazy val akkaJsActor = crossProject.in(file("akka-js-actor"))
         org.akkajs.IrPatcherPlugin.hackAllUnder(classDir, hackDir)

       analysis
-    }
+    },
+    scalaJSOptimizerOptions ~= { _.withCheckScalaJSIR(true) }
   ).jsSettings(
     useAnnotationAdderPluginSettings : _*
   ).jsSettings(
@@ -291,7 +292,8 @@ lazy val akkaActorTest = crossProject.in(file("akka-js-actor-tests"))
     ),
     excludeDependencies += ("org.akka-js" %% "akkaactorjsirpatches"),
     compile in Compile := {(compile in Compile).dependsOn(assembleAkkaLibrary).value},
-    publishLocal := {publishLocal.dependsOn(assembleAkkaLibrary).value}
+    publishLocal := {publishLocal.dependsOn(assembleAkkaLibrary).value},
+    scalaJSOptimizerOptions ~= { _.withCheckScalaJSIR(true) }
  ).dependsOn(akkaJsTestkit % "test->test")

 lazy val akkaActorTestJS = akkaActorTest.js
diff --git a/project/plugins.sbt b/project/plugins.sbt
index ea52c58..26a92f7 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -1,4 +1,4 @@
-val scalaJsVersion = "0.6.16"
+val scalaJsVersion = "0.6.19-SNAPSHOT"

 addSbtPlugin("org.scala-js" % "sbt-scalajs" % scalaJsVersion)

```
Once Scala.js 0.6.19 is released, this should be added to the build in this repo for continuous testing.

**Comment by andreaTP** [comment]
that's really an interesting solution, and it is not more hacky than before,
I have to verify if this apply to all `IRPatched` classes and probably I can get rid of that hack.

Thanks a lot!
LGTM

**Comment by sjrd** [comment]
> I have to verify if this apply to all IRPatched classes

No, it only applies to traits.

**Comment by andreaTP** [comment]
actually the needed fields are all in `trait`s and they got refactored in `ActorCell` because of limitations...

**Pull request merged**
